image:
  - Visual Studio 2015
  - Visual Studio 2017
platform:
  - x86
  - x64
configuration: Debug

environment:
  # Add directory of dll to PATH so Windows can find it
  PATH: $(APPVEYOR_BUILD_FOLDER)\lib\Debug;$(PATH)

before_build:
  cmake . -DREPROC_BUILD_TESTS=ON -DREPROC_BUILD_EXAMPLES=ON
  -DREPROC_BUILD_CXX_WRAPPER=ON -DREPROC_CI=ON -DREPROC_TIDY=ON
  -DREPROC_INSTALL=ON -DREPROC_FORMAT=ON -DBUILD_SHARED_LIBS=ON
  -DREPROC_ENABLE_W4=ON

build_script: cmake --build . --config %CONFIGURATION% -- /p:CL_MPCount=2

test_script: cmake --build . --target reproc-run-tests
